/**
 * Draft climb as edited in the LogSession form (not yet persisted).
 *
 * One entry is one ROUTE for the visit — `attempt_count` tries of which
 * `send_count` topped out — rather than one try, so working a project eight
 * times is one row with an 8, not eight rows.
 *
 * The tag fields hold ids from the master lists; `weakness_labels` holds
 * anything typed into the "other" box, which the server turns into reusable
 * options on save.
 */
export default interface Attempt {
  id: number;
  grade_name: string;
  route_name: string;
  attempt_count: number;
  send_count: number;
  note: string;
  wall_type_ids: number[];
  hold_type_ids: number[];
  weakness_type_ids: number[];
  weakness_labels: string[];
}

/** A route tag as the server returns it alongside a logged climb. */
export interface AttemptTag {
  id: number;
  code: string;
  label: string;
}

/** A weakness as the server returns it alongside a logged climb. */
export interface AttemptWeakness {
  weakness_type_id: number;
  label: string;
}

/**
 * A logged climb as returned by GET /api/v1/attempts — the `attempts` row plus
 * the route name, grade and tags the server joins in for display.
 *
 * `is_success` is generated by the database from `send_count > 0`; it is read
 * here but never sent back.
 */
export interface AttemptRecord {
  attempt_id: number;
  session_id: number;
  route_id: number;
  attempt_count: number;
  send_count: number;
  is_success: boolean;
  note: string | null;
  route_name: string | null;
  grade_name: string;
  grade_level: number;
  wall_types: AttemptTag[];
  hold_types: AttemptTag[];
  weaknesses: AttemptWeakness[];
  created_at: string;
  updated_at: string;
}

/** Sum of tries across a list of climbs — what "total attempts" now means. */
export const totalTries = (attempts: AttemptRecord[]): number =>
  attempts.reduce((sum, a) => sum + a.attempt_count, 0);

/** Sum of sends across a list of climbs. */
export const totalSends = (attempts: AttemptRecord[]): number =>
  attempts.reduce((sum, a) => sum + a.send_count, 0);

/** A route sent on its only try. The figure climbers actually celebrate. */
export const isFlash = (attempt: AttemptRecord): boolean =>
  attempt.attempt_count === 1 && attempt.send_count === 1;
