import { pool, query } from "../db/pool";
import type { PoolClient } from "pg";
import { buildUpdate } from "../utils/buildUpdate";
import { routeRepository } from "./route.repository";
import { weaknessRepository } from "./weakness.repository";

/**
 * Shape of a row in the `attempts` table.
 *
 * Since migration 0007 a row is one ROUTE as logged within a session, not one
 * try: `attempt_count` is how many times it was pulled on and `send_count` how
 * many of those topped out. `is_success` survives as a generated column
 * (`send_count > 0`), which is what let every existing read keep working
 * through that change.
 */
export interface Attempt {
  attempt_id: number;
  session_id: number;
  route_id: number;
  attempt_count: number;
  send_count: number;
  /** Generated by the database — never written directly. */
  is_success: boolean;
  note: string | null;
  created_at: string;
  updated_at: string;
}

/** A tag as returned alongside an attempt. */
export interface AttemptTag {
  id: number;
  code: string;
  label: string;
}

/** A weakness as returned alongside an attempt (no code — labels are free text). */
export interface AttemptWeakness {
  weakness_type_id: number;
  label: string;
}

/**
 * An attempt as the /attempts endpoints return it: the row itself plus the
 * route name, grade and tags joined in, so clients can display a logged climb
 * without fetching four more collections.
 */
export interface AttemptWithRoute extends Attempt {
  route_name: string | null;
  grade_name: string;
  grade_level: number;
  wall_types: AttemptTag[];
  hold_types: AttemptTag[];
  weaknesses: AttemptWeakness[];
}

/**
 * Everything one PATCH of a logged climb can touch.
 *
 * It spans three tables — the attempt, the route behind it, and the two tag
 * join tables — which is why it is one input rather than several: they are
 * written together or not at all.
 *
 * `undefined` means "leave alone" throughout. An empty array is therefore how a
 * climber clears their tags, and is not the same as omitting the field.
 *
 * Not here: `is_success`, generated from send_count, and `route_id`, because
 * repointing an attempt at an arbitrary route was a way to read and rewrite
 * another climber's route. Correcting the route is what grade_id/route_name
 * are for, and they only ever reach this attempt's own.
 */
export interface UpdateAttemptInput {
  attempt_count?: number;
  send_count?: number;
  note?: string | null;
  grade_id?: number;
  route_name?: string | null;
  wall_type_ids?: number[];
  hold_type_ids?: number[];
  /** Already resolved to ids by the controller, free-text labels included. */
  weakness_type_ids?: number[];
}

/**
 * The tag columns, as correlated subqueries rather than extra JOINs.
 *
 * Joining three many-to-many tables into one row set would multiply out — an
 * attempt with 2 wall types and 3 hold types would come back 6 times and every
 * count downstream would be wrong. Aggregating each tag list in its own
 * scalar subquery keeps the result exactly one row per attempt.
 */
const TAG_COLUMNS = `
  COALESCE((
    SELECT json_agg(json_build_object('id', wt.wall_type_id, 'code', wt.code, 'label', wt.label)
                    ORDER BY wt.sort_order)
      FROM route_wall_types rwt
      JOIN wall_types wt USING (wall_type_id)
     WHERE rwt.route_id = a.route_id
  ), '[]'::json) AS wall_types,
  COALESCE((
    SELECT json_agg(json_build_object('id', ht.hold_type_id, 'code', ht.code, 'label', ht.label)
                    ORDER BY ht.sort_order)
      FROM route_hold_types rht
      JOIN hold_types ht USING (hold_type_id)
     WHERE rht.route_id = a.route_id
  ), '[]'::json) AS hold_types,
  COALESCE((
    SELECT json_agg(json_build_object('weakness_type_id', w.weakness_type_id, 'label', w.label)
                    ORDER BY w.sort_order, w.label)
      FROM attempt_weaknesses aw
      JOIN weakness_types w USING (weakness_type_id)
     WHERE aw.attempt_id = a.attempt_id
  ), '[]'::json) AS weaknesses`;

/**
 * Data-access layer for attempts. Every SQL statement here is parameterized
 * ($1, $2, ...) so values are never concatenated into the query string.
 *
 * Attempts have no user_id column — ownership flows through the parent
 * session, so every query joins/filters on sessions.user_id. The controller
 * passes the user_id from the verified token.
 */
export const attemptRepository = {
  /** List the user's logged climbs, optionally scoped to one of their sessions. */
  async findAll(
    userId: number,
    sessionId?: number,
  ): Promise<AttemptWithRoute[]> {
    const values: unknown[] = [userId];
    let where = `WHERE s.user_id = $1`;
    if (sessionId !== undefined) {
      values.push(sessionId);
      where += ` AND a.session_id = $${values.length}`;
    }
    const { rows } = await query<AttemptWithRoute>(
      `SELECT a.*, r.route_name, g.grade_name, g.level AS grade_level,
              ${TAG_COLUMNS}
       FROM attempts a
       JOIN sessions s USING (session_id)
       JOIN routes r USING (route_id)
       JOIN grades g USING (grade_id)
       ${where}
       ORDER BY a.attempt_id DESC`,
      values,
    );
    return rows;
  },

  async findById(id: number, userId: number): Promise<AttemptWithRoute | null> {
    const { rows } = await query<AttemptWithRoute>(
      `SELECT a.*, r.route_name, g.grade_name, g.level AS grade_level,
              ${TAG_COLUMNS}
       FROM attempts a
       JOIN sessions s USING (session_id)
       JOIN routes r USING (route_id)
       JOIN grades g USING (grade_id)
       WHERE a.attempt_id = $1 AND s.user_id = $2`,
      [id, userId],
    );
    return rows[0] ?? null;
  },

  /**
   * Partial update of one logged climb, in a single transaction.
   *
   * Editing a climb writes to four tables: the attempt's counts and note, the
   * route's grade and name, and the two tag join tables. These used to be
   * separate calls on separate pooled connections, so a failure partway through
   * left the counts saved against the old tags — a V4 whose grade had been
   * corrected to V5 but whose wall angle still said the previous one, with
   * nothing to indicate the edit had half-failed. One client, one transaction,
   * so the climb is either as the climber left it or exactly as they found it.
   *
   * Only the fields provided are written; see utils/buildUpdate. Returns null
   * when the climb is not the caller's, which reads as missing.
   */
  async update(
    id: number,
    userId: number,
    input: UpdateAttemptInput,
  ): Promise<AttemptWithRoute | null> {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");

      // Ownership is a join rather than an equality, because attempts carry no
      // user_id of their own — it lives on the parent session. The route id
      // comes back with it, so nothing downstream has to look it up again.
      const { rows: owned } = await client.query<{ route_id: number }>(
        `SELECT a.route_id
           FROM attempts a
           JOIN sessions s USING (session_id)
          WHERE a.attempt_id = $1 AND s.user_id = $2`,
        [id, userId],
      );
      const routeId = owned[0]?.route_id;
      if (routeId === undefined) {
        await client.query("ROLLBACK");
        return null;
      }

      const attemptUpdate = buildUpdate(
        "attempts",
        {
          attempt_count: input.attempt_count,
          send_count: input.send_count,
          note: input.note,
        },
        { attempt_id: id },
      );
      if (attemptUpdate) {
        await client.query(attemptUpdate.text, attemptUpdate.values);
      }

      const routeUpdate = buildUpdate(
        "routes",
        { grade_id: input.grade_id, route_name: input.route_name },
        { route_id: routeId },
      );
      if (routeUpdate) {
        await client.query(routeUpdate.text, routeUpdate.values);
      }

      // Tags hang off the route, weaknesses off the attempt. Both replace in
      // full, so an empty array is how a climber clears them and `undefined`
      // leaves them alone.
      if (input.wall_type_ids !== undefined || input.hold_type_ids !== undefined) {
        await this.setRouteTags(
          routeId,
          {
            wallTypeIds: input.wall_type_ids,
            holdTypeIds: input.hold_type_ids,
          },
          client,
        );
      }
      if (input.weakness_type_ids !== undefined) {
        await weaknessRepository.setForAttempt(
          id,
          input.weakness_type_ids,
          client,
        );
      }

      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      client.release();
    }

    // Re-read rather than RETURNING *: the response carries the joined route,
    // grade and three tag lists, none of which RETURNING can produce.
    return this.findById(id, userId);
  },

  /**
   * Delete one logged climb, and the route behind it if nothing else points at
   * it. `routes` is the parent side of the foreign key, so without the second
   * step every deleted climb leaves a row nobody can ever reach again.
   */
  async remove(id: number, userId: number): Promise<boolean> {
    const { rows } = await query<{ route_id: number }>(
      `DELETE FROM attempts
       WHERE attempt_id = $1
         AND session_id IN (SELECT session_id FROM sessions WHERE user_id = $2)
       RETURNING route_id`,
      [id, userId],
    );
    if (rows.length === 0) return false;

    await routeRepository.removeOrphans(rows.map((r) => r.route_id));
    return true;
  },

  /**
   * Replace the wall/hold tags on the route behind an attempt. Delete-then-
   * insert rather than a diff: the sets are at most a handful of rows, and it
   * makes "cleared every tag" work without a special case.
   */
  async setRouteTags(
    routeId: number,
    tags: { wallTypeIds?: number[]; holdTypeIds?: number[] },
    client?: PoolClient,
  ): Promise<void> {
    const exec = client ?? pool;
    if (tags.wallTypeIds !== undefined) {
      await exec.query(`DELETE FROM route_wall_types WHERE route_id = $1`, [routeId]);
      if (tags.wallTypeIds.length > 0) {
        await exec.query(
          `INSERT INTO route_wall_types (route_id, wall_type_id)
           SELECT $1, unnest($2::int[]) ON CONFLICT DO NOTHING`,
          [routeId, tags.wallTypeIds],
        );
      }
    }
    if (tags.holdTypeIds !== undefined) {
      await exec.query(`DELETE FROM route_hold_types WHERE route_id = $1`, [routeId]);
      if (tags.holdTypeIds.length > 0) {
        await exec.query(
          `INSERT INTO route_hold_types (route_id, hold_type_id)
           SELECT $1, unnest($2::int[]) ON CONFLICT DO NOTHING`,
          [routeId, tags.holdTypeIds],
        );
      }
    }
  },
};
