import { pool, query } from "../db/pool";
import type { PoolClient } from "pg";

/**
 * Shape of a row in the `attempts` table.
 *
 * Since migration 0007 a row is one ROUTE as logged within a session, not one
 * try: `attempt_count` is how many times it was pulled on and `send_count` how
 * many of those topped out. `is_success` survives as a generated column
 * (`send_count > 0`), which is what let every existing read keep working
 * through that change.
 */
export interface Attempt {
  attempt_id: number;
  session_id: number;
  route_id: number;
  attempt_count: number;
  send_count: number;
  /** Generated by the database — never written directly. */
  is_success: boolean;
  note: string | null;
  created_at: string;
  updated_at: string;
}

/** A tag as returned alongside an attempt. */
export interface AttemptTag {
  id: number;
  code: string;
  label: string;
}

/** A weakness as returned alongside an attempt (no code — labels are free text). */
export interface AttemptWeakness {
  weakness_type_id: number;
  label: string;
}

/**
 * An attempt as the /attempts endpoints return it: the row itself plus the
 * route name, grade and tags joined in, so clients can display a logged climb
 * without fetching four more collections.
 */
export interface AttemptWithRoute extends Attempt {
  route_name: string | null;
  grade_name: string;
  grade_level: number;
  wall_types: AttemptTag[];
  hold_types: AttemptTag[];
  weaknesses: AttemptWeakness[];
}

export interface UpdateAttemptInput {
  route_id?: number;
  attempt_count?: number;
  send_count?: number;
  note?: string | null;
}

/**
 * The tag columns, as correlated subqueries rather than extra JOINs.
 *
 * Joining three many-to-many tables into one row set would multiply out — an
 * attempt with 2 wall types and 3 hold types would come back 6 times and every
 * count downstream would be wrong. Aggregating each tag list in its own
 * scalar subquery keeps the result exactly one row per attempt.
 */
const TAG_COLUMNS = `
  COALESCE((
    SELECT json_agg(json_build_object('id', wt.wall_type_id, 'code', wt.code, 'label', wt.label)
                    ORDER BY wt.sort_order)
      FROM route_wall_types rwt
      JOIN wall_types wt USING (wall_type_id)
     WHERE rwt.route_id = a.route_id
  ), '[]'::json) AS wall_types,
  COALESCE((
    SELECT json_agg(json_build_object('id', ht.hold_type_id, 'code', ht.code, 'label', ht.label)
                    ORDER BY ht.sort_order)
      FROM route_hold_types rht
      JOIN hold_types ht USING (hold_type_id)
     WHERE rht.route_id = a.route_id
  ), '[]'::json) AS hold_types,
  COALESCE((
    SELECT json_agg(json_build_object('weakness_type_id', w.weakness_type_id, 'label', w.label)
                    ORDER BY w.sort_order, w.label)
      FROM attempt_weaknesses aw
      JOIN weakness_types w USING (weakness_type_id)
     WHERE aw.attempt_id = a.attempt_id
  ), '[]'::json) AS weaknesses`;

/**
 * Data-access layer for attempts. Every SQL statement here is parameterized
 * ($1, $2, ...) so values are never concatenated into the query string.
 *
 * Attempts have no user_id column — ownership flows through the parent
 * session, so every query joins/filters on sessions.user_id. The controller
 * passes the user_id from the verified token.
 */
export const attemptRepository = {
  /** List the user's logged climbs, optionally scoped to one of their sessions. */
  async findAll(
    userId: number,
    sessionId?: number,
  ): Promise<AttemptWithRoute[]> {
    const values: unknown[] = [userId];
    let where = `WHERE s.user_id = $1`;
    if (sessionId !== undefined) {
      values.push(sessionId);
      where += ` AND a.session_id = $${values.length}`;
    }
    const { rows } = await query<AttemptWithRoute>(
      `SELECT a.*, r.route_name, g.grade_name, g.level AS grade_level,
              ${TAG_COLUMNS}
       FROM attempts a
       JOIN sessions s USING (session_id)
       JOIN routes r USING (route_id)
       JOIN grades g USING (grade_id)
       ${where}
       ORDER BY a.attempt_id DESC`,
      values,
    );
    return rows;
  },

  async findById(id: number, userId: number): Promise<AttemptWithRoute | null> {
    const { rows } = await query<AttemptWithRoute>(
      `SELECT a.*, r.route_name, g.grade_name, g.level AS grade_level,
              ${TAG_COLUMNS}
       FROM attempts a
       JOIN sessions s USING (session_id)
       JOIN routes r USING (route_id)
       JOIN grades g USING (grade_id)
       WHERE a.attempt_id = $1 AND s.user_id = $2`,
      [id, userId],
    );
    return rows[0] ?? null;
  },

  /**
   * Partial update. Builds the SET clause only from the fields provided so a
   * missing field is left untouched (rather than overwritten with NULL).
   *
   * `is_success` is not updatable: it is generated from send_count, so sending
   * a send_count is how a climb is marked sent.
   */
  async update(
    id: number,
    userId: number,
    input: UpdateAttemptInput,
  ): Promise<AttemptWithRoute | null> {
    const fields: string[] = [];
    const values: unknown[] = [];

    const push = (column: string, value: unknown) => {
      values.push(value);
      fields.push(`${column} = $${values.length}`);
    };

    if (input.route_id !== undefined) push("route_id", input.route_id);
    if (input.attempt_count !== undefined) push("attempt_count", input.attempt_count);
    if (input.send_count !== undefined) push("send_count", input.send_count);
    if (input.note !== undefined) push("note", input.note);

    if (fields.length === 0) {
      return this.findById(id, userId);
    }

    values.push(id);
    const idIdx = values.length;
    values.push(userId);
    const userIdx = values.length;

    const { rowCount } = await query(
      `UPDATE attempts SET ${fields.join(", ")}
       WHERE attempt_id = $${idIdx}
         AND session_id IN (SELECT session_id FROM sessions WHERE user_id = $${userIdx})`,
      values,
    );
    if ((rowCount ?? 0) === 0) return null;
    // Re-read rather than RETURNING *: the response carries joined route, grade
    // and three tag lists, none of which RETURNING can produce.
    return this.findById(id, userId);
  },

  async remove(id: number, userId: number): Promise<boolean> {
    const { rowCount } = await query(
      `DELETE FROM attempts
       WHERE attempt_id = $1
         AND session_id IN (SELECT session_id FROM sessions WHERE user_id = $2)`,
      [id, userId],
    );
    return (rowCount ?? 0) > 0;
  },

  /**
   * Replace the wall/hold tags on the route behind an attempt. Delete-then-
   * insert rather than a diff: the sets are at most a handful of rows, and it
   * makes "cleared every tag" work without a special case.
   */
  async setRouteTags(
    routeId: number,
    tags: { wallTypeIds?: number[]; holdTypeIds?: number[] },
    client?: PoolClient,
  ): Promise<void> {
    const exec = client ?? pool;
    if (tags.wallTypeIds !== undefined) {
      await exec.query(`DELETE FROM route_wall_types WHERE route_id = $1`, [routeId]);
      if (tags.wallTypeIds.length > 0) {
        await exec.query(
          `INSERT INTO route_wall_types (route_id, wall_type_id)
           SELECT $1, unnest($2::int[]) ON CONFLICT DO NOTHING`,
          [routeId, tags.wallTypeIds],
        );
      }
    }
    if (tags.holdTypeIds !== undefined) {
      await exec.query(`DELETE FROM route_hold_types WHERE route_id = $1`, [routeId]);
      if (tags.holdTypeIds.length > 0) {
        await exec.query(
          `INSERT INTO route_hold_types (route_id, hold_type_id)
           SELECT $1, unnest($2::int[]) ON CONFLICT DO NOTHING`,
          [routeId, tags.holdTypeIds],
        );
      }
    }
  },
};
